In [2]:
import numpy as np
import torch
import tensorflow as tf

In [3]:
K = np.array([[2/3, 1/3, 2/3], [-2/3, 2/3, 1/3], [1/3, 2/3, -2/3]])
K

array([[ 0.66666667,  0.33333333,  0.66666667],
       [-0.66666667,  0.66666667,  0.33333333],
       [ 0.33333333,  0.66666667, -0.66666667]])

In [4]:
K_pt = torch.tensor([[2/3, 1/3, 2/3], [-2/3, 2/3, 1/3], [1/3, 2/3, -2/3]])
K_pt

tensor([[ 0.6667,  0.3333,  0.6667],
        [-0.6667,  0.6667,  0.3333],
        [ 0.3333,  0.6667, -0.6667]])

In [5]:
K_tf = tf.Variable([[2/3, 1/3, 2/3], [-2/3, 2/3, 1/3], [1/3, 2/3, -2/3]])
K_tf

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[ 0.6666667 ,  0.33333334,  0.6666667 ],
       [-0.6666667 ,  0.6666667 ,  0.33333334],
       [ 0.33333334,  0.6666667 , -0.6666667 ]], dtype=float32)>

In [6]:
K.T

array([[ 0.66666667, -0.66666667,  0.33333333],
       [ 0.33333333,  0.66666667,  0.66666667],
       [ 0.66666667,  0.33333333, -0.66666667]])

In [8]:
np.dot(K.T, K)

array([[1.00000000e+00, 1.54197642e-17, 1.23358114e-17],
       [1.54197642e-17, 1.00000000e+00, 2.46716228e-17],
       [1.23358114e-17, 2.46716228e-17, 1.00000000e+00]])