In [1]:
import numpy as np
import torch
import tensorflow as tf

In [4]:
X = np.array([[4, 2], [-5, -3]])
X

array([[ 4,  2],
       [-5, -3]])

In [6]:
Xinv = np.linalg.inv(X)
Xinv

array([[ 1.5,  1. ],
       [-2.5, -2. ]])

In [9]:
np.dot(Xinv,X)

array([[1.00000000e+00, 3.33066907e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [10]:
np.dot(X, Xinv)

array([[ 1.0000000e+00, -4.4408921e-16],
       [ 4.4408921e-16,  1.0000000e+00]])