In [1]:
import numpy as np
import torch
import tensorflow as tf

In [9]:
X = np.array([[25, 2], [5, 6], [3, 2]])
X_pt = torch.tensor([[25, 2], [5, 6], [3, 2.]])
X_tf = tf.Variable([[25, 2], [5, 6], [3, 2.]])

In [7]:
np.linalg.norm(X)

26.514147167125703

In [10]:
torch.norm(X_pt)

tensor(26.5141)

In [11]:
tf.norm(X_tf)

<tf.Tensor: shape=(), dtype=float32, numpy=26.514147>

In [13]:
A = np.array([[3, 4], [5, 6], [7, 8]])
A

array([[3, 4],
       [5, 6],
       [7, 8]])

In [19]:
b = np.array([1, 2])
b

array([1, 2])

In [20]:
np.dot(A,b)

array([11, 17, 23])

In [26]:
A_pt = torch.tensor([[3, 4], [5, 6], [7, 8]])
A_tf = tf.Variable([[3, 4], [5, 6], [7, 8]])
b_pt = torch.tensor([1, 2])
b_tf = tf.Variable([1, 2])

In [27]:
torch.matmul(A_pt, b_pt)

tensor([11, 17, 23])

In [29]:
tf.linalg.matvec(A_pt, b_pt)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([11, 17, 23], dtype=int64)>

In [31]:
B = np.array([[1, 9], [2, 0]])
B

array([[1, 9],
       [2, 0]])

In [33]:
np.dot(A, B)

array([[11, 27],
       [17, 45],
       [23, 63]])

In [39]:
B_pt = torch.from_numpy(B)
B_pt

tensor([[1, 9],
        [2, 0]], dtype=torch.int32)

In [40]:
torch.matmul(A_pt, B_pt)

RuntimeError: expected m1 and m2 to have the same dtype, but got: __int64 != int