In [2]:
import numpy as np
import torch
import tensorflow as tf

In [4]:
X = np.array([[25, 2], [12, 1], [3, 5]])
X_pt = torch.tensor([[25, 2], [12, 1], [3, 5]])
X_tf = tf.Variable([[25, 2], [12, 1], [3, 5]])

In [7]:
X.T
X_pt.T
tf.transpose(X_tf)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[25, 12,  3],
       [ 2,  1,  5]])>

In [10]:
X * 2
X_pt * 2
tf.multiply(X_tf, 2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[50,  4],
       [24,  2],
       [ 6, 10]])>

In [15]:
X.sum()
torch.sum(X_pt)
tf.reduce_sum(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=48>

In [20]:
X.sum(axis = 0)
X.sum(axis = 1)
torch.sum(X_pt, 0)
tf.reduce_sum(X_tf, 1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([27, 13,  8])>

In [21]:
x = 2
y = np.array([25, 2, 5])

np.dot(x, y)

array([50,  4, 10])

In [22]:
x_pt = torch.tensor([25, 2, 5])
np.dot(x_pt, x)

array([50,  4, 10], dtype=int64)

In [23]:
x_tf = tf.Variable([25, 2, 5])
tf.reduce_sum(tf.multiply(x_tf, x))

<tf.Tensor: shape=(), dtype=int32, numpy=64>