In [67]:
import torch

In [68]:
A_pt = torch.tensor([[-1, 2], [3, -2], [5, 7.]])
A_pt

tensor([[-1.,  2.],
        [ 3., -2.],
        [ 5.,  7.]])

In [73]:
U, d, VT = torch.linalg.svd(A_pt)

In [74]:
U

tensor([[ 0.1271,  0.4741,  0.8713],
        [ 0.0016, -0.8785,  0.4778],
        [ 0.9919, -0.0593, -0.1124]])

In [75]:
d

tensor([8.6692, 4.1043])

In [76]:
VT

tensor([[ 0.5580,  0.8298],
        [-0.8298,  0.5580]])

In [77]:
UT = torch.transpose(U, dim0 = 0, dim1 = 1)
UT

tensor([[ 0.1271,  0.0016,  0.9919],
        [ 0.4741, -0.8785, -0.0593],
        [ 0.8713,  0.4778, -0.1124]])

In [78]:
D = torch.diag(d)
D

tensor([[8.6692, 0.0000],
        [0.0000, 4.1043]])

In [79]:
Dinv = torch.linalg.inv(D)
Dinv

tensor([[0.1154, 0.0000],
        [0.0000, 0.2436]])

In [87]:
Dplus = torch.cat([Dinv, torch.transpose(
    torch.tensor([[0, 0]]), dim0=0, dim1=1)], axis=1)
Dplus

tensor([[0.1154, 0.0000, 0.0000],
        [0.0000, 0.2436, 0.0000]])

In [88]:
V = torch.transpose(VT, dim0 = 0, dim1 = 1)
V

tensor([[ 0.5580, -0.8298],
        [ 0.8298,  0.5580]])

In [89]:
torch.mm(V, torch.mm(Dplus, UT))

tensor([[-0.0877,  0.1777,  0.0758],
        [ 0.0766, -0.1193,  0.0869]])

In [90]:
torch.pinverse(A_pt)

tensor([[-0.0877,  0.1777,  0.0758],
        [ 0.0766, -0.1193,  0.0869]])