In [ ]:
import numpy as np
import torch
import tensorflow as tf

In [ ]:
A = np.array([[-4, 1], [-8, 2]])
A

In [ ]:
np.linalg.det(A)

In [ ]:
A_pt = torch.tensor([[-4, 1], [-8, 2]])
A_pt

In [ ]:
torch.det(A_pt)

In [9]:
B = np.array([[1, 0], [0, 1]])
B

array([[1, 0],
       [0, 1]])

In [11]:
N = np.array([[-4, 1], [-8, 2.]])
N

array([[-4.,  1.],
       [-8.,  2.]])

In [13]:
np.linalg.det(N)

0.0

In [16]:
NB = np.dot(N, B)
NB

array([[-4.,  1.],
       [-8.,  2.]])

In [17]:
lambdas, V = np.linalg.eig(N)
lambdas

array([-2.,  0.])

In [19]:
J = np.array([[-0.5, 0], [0, 2]])
np.linalg.det(J)

-1.0

In [20]:
JB = np.dot(J, B)

In [22]:
JB

array([[-0.5,  0. ],
       [ 0. ,  2. ]])

In [26]:
I = np.array([[1, 0], [0, 1]])
D = I * 2
D

array([[2, 0],
       [0, 2]])

In [28]:
np.linalg.det(D)

4.0

In [30]:
DB = np.dot(D, B)
DB

array([[2, 0],
       [0, 2]])

In [32]:
lambdas, V = np.linalg.eig(D)
lambdas

array([2., 2.])