In [1]:
import numpy as np
import torch
import tensorflow as tf

In [3]:
A = np.array([[-1, 4], [2, -2]])
A

array([[-1,  4],
       [ 2, -2]])

In [4]:
lambdas, V = np.linalg.eig(A)

In [6]:
lambdas

array([ 1.37228132, -4.37228132])

In [7]:
V

array([[ 0.86011126, -0.76454754],
       [ 0.51010647,  0.64456735]])

In [9]:
v = V[:, 0]
v

array([0.86011126, 0.51010647])

In [10]:
lambda1 = lambdas[0]
lambda1

1.3722813232690143

In [12]:
Av = np.dot(A, v)
Av

array([1.18031462, 0.70000958])

In [13]:
Av == lambda1 * v

array([ True,  True])

In [20]:
A_p = torch.tensor([[-1, 4], [2, -2.]])
A_p

tensor([[-1.,  4.],
        [ 2., -2.]])

In [24]:
eigens = torch.linalg.eig(A_p)
eigens[0]

tensor([ 1.3723+0.j, -4.3723+0.j])