In [11]:
import numpy as np
import torch
import tensorflow as tf

In [12]:
X = np.array([[25, 2], [5, 26], [9, 7]])
X

array([[25,  2],
       [ 5, 26],
       [ 9,  7]])

In [13]:
X.shape

(3, 2)

In [14]:
X.size

6

In [15]:
X[:,0]

array([25,  5,  9])

In [17]:
X[1,:]

array([ 5, 26])

In [18]:
X[0:2, 0:2]

array([[25,  2],
       [ 5, 26]])

In [20]:
X_pt = torch.tensor([[25, 2], [5, 26], [3, 7]])
X_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [22]:
X_pt.shape

torch.Size([3, 2])

In [25]:
X_pt[1,:]

tensor([ 5, 26])

In [27]:
X_tf = tf.Variable([[25, 2], [5, 36], [1, 6]])
X_tf.shape

TensorShape([3, 2])

In [28]:
tf.rank(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [29]:
X_tf[1,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 5, 36])>