In [37]:
import numpy as np
import torch
import tensorflow as tf

In [9]:
x = np.array([25, 2, 5])
x

array([25,  2,  5])

In [11]:
len(x)

3

In [13]:
x.shape

(3,)

In [15]:
type(x)

numpy.ndarray

In [17]:
x[0]

25

In [19]:
type(x[0])

numpy.int32

In [21]:
x_t = x.T
x_t

array([25,  2,  5])

In [23]:
x_t.shape

(3,)

In [26]:
y = np.array([[25, 2, 5]])
y

array([[25,  2,  5]])

In [29]:
y.shape

(1, 3)

In [31]:
y_t = y.T
y_t

array([[25],
       [ 2],
       [ 5]])

In [32]:
y_t.shape

(3, 1)

In [34]:
z = np.zeros(3)
z

array([0., 0., 0.])

In [38]:
x_pt = torch.tensor([25, 2, 5])
x_pt

tensor([25,  2,  5])

In [40]:
x_tf = tf.Variable([25, 2, 5])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([25,  2,  5])>